# Generated by Django 2.2.5 on 2022-01-25 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('content', models.CharField(max_length=400)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('hit_cnt', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='brduser_id')),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_idx', models.IntegerField()),
                ('stored_file_name', models.CharField(max_length=45)),
                ('file_size', models.IntegerField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='fleuser_id')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_num', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=45)),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board', verbose_name='cmtboard_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cmtuser_id')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
