# Generated by Django 4.0.1 on 2022-01-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='id',
        ),
        migrations.AlterField(
            model_name='board',
            name='board_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='hit_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_idx',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
