# Generated by Django 4.0.1 on 2022-01-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_file_id_alter_board_board_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user_id',
            new_name='username',
        ),
    ]
