# Generated by Django 4.0.1 on 2022-01-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_comment_board_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterModelTable(
            name='notice',
            table='notice',
        ),
    ]
