# Generated by Django 4.0.1 on 2022-01-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_user_id_board_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='username',
            new_name='user_id',
        ),
    ]
