# Generated by Django 4.0.1 on 2022-01-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_date'),
        ('board', '0004_rename_username_board_user_id'),
    ]

    operations = [
    ]
