# Generated by Django 4.0.1 on 2022-01-26 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_merge_20220126_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('content', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hit_cnt', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='board',
            name='hit_cnt',
        ),
        migrations.RemoveField(
            model_name='board',
            name='like',
        ),
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
